language: python

notifications:
  email:
    recipients:
      - astepano@redhat.com

python:
    - "2.7_with_system_site_packages"
    - "2.6"

branches:
    only:
        - master

sudo: false

install:
    - pip install "Sphinx==1.3b1"
    - pip install -r requirements-travis.txt

script:
    # If exclude is specified, it is necesssary to list all default extensions
    - inspekt --exclude=.git lint --disable W,R,C,E0012,E1002,E1101,E1103,E1120,F0401,I0011 --enable W0611
    - inspekt indent
    - inspekt --exclude=.git style --disable E124,E265,E402,E501
