language: python

notifications:
  email:
    recipients:
      - astepano@redhat.com

python:
    - "2.7_with_system_site_packages"
    - "3.4"

matrix:
  allow_failures:
    - python: "3.4"

branches:
    only:
        - master

sudo: false

install:
    - pip install "Sphinx==1.3b1"
    - pip install -r requirements-travis.txt

script:
    - inspekt checkall --exclude=.git --no-license-check
